package middleware

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/Raoon-Soluciones/bpmn-ai/internal/observability"
)

func TestRequestLogger(t *testing.T) {
	logger, _ := observability.NewFromConfig("error", "text")
	metrics := observability.NewMetrics()

	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("ok"))
	})

	mw := RequestLogger(logger, metrics)
	req := httptest.NewRequest(http.MethodGet, "/test", nil)
	rec := httptest.NewRecorder()

	mw(handler).ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rec.Code)
	}
	if rec.Body.String() != "ok" {
		t.Errorf("expected body 'ok', got %s", rec.Body.String())
	}
}

func TestRequestLogger_WithErrorStatus(t *testing.T) {
	logger, _ := observability.NewFromConfig("error", "text")
	metrics := observability.NewMetrics()

	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
	})

	mw := RequestLogger(logger, metrics)
	req := httptest.NewRequest(http.MethodGet, "/error", nil)
	rec := httptest.NewRecorder()

	mw(handler).ServeHTTP(rec, req)

	if rec.Code != http.StatusInternalServerError {
		t.Errorf("expected 500, got %d", rec.Code)
	}
}

func TestRequestID_CustomHeader(t *testing.T) {
	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		reqID := GetRequestID(r.Context())
		if reqID == "" {
			reqID = r.Header.Get("X-Request-ID")
		}
		w.Header().Set("X-Echo-ID", reqID)
	})

	mw := RequestID
	req := httptest.NewRequest(http.MethodGet, "/test", nil)
	req.Header.Set("X-Request-ID", "custom-123")
	rec := httptest.NewRecorder()

	mw(handler).ServeHTTP(rec, req)

	if rec.Header().Get("X-Echo-ID") != "custom-123" {
		t.Errorf("expected custom-123, got %s", rec.Header().Get("X-Echo-ID"))
	}
}

func TestRequestID_AutoGenerated(t *testing.T) {
	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		reqID := GetRequestID(r.Context())
		w.Header().Set("X-Echo-ID", reqID)
	})

	mw := RequestID
	req := httptest.NewRequest(http.MethodGet, "/test", nil)
	rec := httptest.NewRecorder()

	mw(handler).ServeHTTP(rec, req)

	reqID := rec.Header().Get("X-Echo-ID")
	if reqID == "" {
		t.Error("expected auto-generated request ID")
	}
	if len(reqID) < 10 {
		t.Errorf("expected non-empty request ID, got %s", reqID)
	}
}

func TestGetRequestID_EmptyContext(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/test", nil)
	reqID := GetRequestID(req.Context())
	if reqID != "" {
		t.Errorf("expected empty string for context without request ID, got %s", reqID)
	}
}
